### ISSUE TITLE
Система аутентификции

### ISSUE THREAD

**Issue by Rashid-ad-din** [Rashid-ad-din/homework_68_rashid_gulamov#1]
### Для чего это нужно
Система аутентификации необходима для идентификации пользователей в системе и предоставлении функционала на основе идентифицированного пользователя и его роли.

### Как это сделать
Создать страницу регистрации пользователя.
Страница должна быть доступна по адресу _host/auth/register_

`При регистрации пользователя ему предоставляется возможность выбрать в роли кого он регистрируется. это может быть выпадающий список или же радиобаттоны, решать вам. Форма регистрации включает в себя небольшой набор полей, такие как имя пользователя / при выборе роли компания необходимо с помощью jQuery / JS изменять содержимое формы, в данном случае текст в label на Имя компании. 

Обязательными полями при регистрации также являются email , номер телефона.  Фото профиля к загрузке не обязательно, но такая возможность должна быть. В случае если фото не загружено, следует устанавливать изображение по умолчанию.`

Форма включает в себя следующий набор полей:
Email *
Номер телефона *
Имя / Название компании *
Файловое поле (Фото)
Пароль *
Подтверждение пароля *

#### Создать страницу аутентификации
Страница должна быть доступна по адресу _host/auth/login_

Для входа в систему предлагается форма с двумя полями:
Email *
Пароль *
Кнопка войти

### Критерии приема

**Регистрация пользователя**
Добавлена ссылка на регистрацию.
Переход по ссылке открывает форму регистрации.
При корректном заполнении формы нажатие на кнопку зарегистрироваться создает учетную запись пользователя и запускает его в систему.
При выборе пользователя как _компании_, label **Имя** (поле username) меняется на **Имя компании**, аналогично при выборе как _пользователя_, текст меняется на **Имя кандидата**.
Также, автоматически добавляется группа пользователя, company или candidate.

**Логин**
Добавлена ссылка на логин (отображается неавторизованному пользователю).
Переход по ссылке открывает форму логина.
При корректном заполнении формы нажатие на кнопку войти авторизует пользователя и запускает его в систему.
Пользователь видит свой профиль.

**Выход**
Кнопка выход (отображается авторизованному пользователю).
Нажатие на кнопку выход выводит пользователя из системы и переадресует на форму входа.
Пользователь видит форму входа.

**Comment by Rashid-ad-din** [comment]
Завершена задача #1. Затраченное чистое время 4 часа.  1 час ушел на изменение текста label поля username посредством js. Коммит занял 1 час.
Прошу принять задачу на проверку.

**Comment by kurentaev** [comment]
Система аутентификации выполнена в полной мере. Работа принимается.
