### ISSUE TITLE
Создание CRUD операций для модели Резюме, Опыт работы, Образование.

### ISSUE THREAD

**Issue by Rashid-ad-din** [Rashid-ad-din/homework_68_rashid_gulamov#10]
**Для чего это нужно :**
Обеспечивает возможность создания, редактирования, удаления, детального просмотра резюме.

**Как это сделать:**
Создание путей, шаблонов, вьюшек, форм.

Поля для моделей при создании/редактировании резюме.

**Resume:**
Автор *
Имя *
Фамилия *
Позиция *
Сфера деятельности (Категория) *
Уровень дохода *
Телефон *
Email *
Telegram *
Facebook
Linkedin
Опыт работы (M2M webapp.Experiences)
Образование (webapp.Educations)
Обо мне
Активность резюме (отражать или нет данное резюме) *
CategoryChoices:
Произвольные чойсы, отражающие сферу деятельности в которой работает кандидат.

**Education:**
Наименование образовательного учреждения *
Дата начала обучения *
Дата окончания обучения *
Специальность *
Дополнительная информация

**Experience :**
Компания *
Стаж *
Дата начала *
Дата увольнения *
Позиция *
Обязанности *
Дополнительная информация

**Критерии приема :**
При создании экземпляров моделей в браузере они не смогут быть созданы без заполнения обязательных полей.
Резюме создается поэтапно. В первую очередь заполняется основная информация. Далее по желанию, опыт работы и образование.
Поля модели Резюме _опыт работы_ и _образование_ связываются с соответствующими моделями связью М2М и являются необязательными, т.к. кандидат может не иметь опыта работы и, теоретически, не иметь образования.
На странице отображения резюме, нажав на кнопки можно редактировать блок основной информации, блок образования, блок опыта работы, также добавлять место работы/обучения. Данный функционал позволит в указать несколько мест обучений и/или компаний в которых работал соискатель.

Планируемое время : 4 часа.

**Comment by Rashid-ad-din** [comment]
Задача завершена. Затраченное время - около 8 часов. Неправильный подход при создании операции редактирования модулей через модальное окно на странице детального просмотра резюме. В конечном итоге примененые вьюшки с ссылкой на отдельные страницы.

**Comment by kurentaev** [comment]
Задача выполнена в полной мере. Работа принимается.
