### ISSUE TITLE
Создание CRUD операций для модели Вакансии.

### ISSUE THREAD

**Issue by kurentaev** [Rashid-ad-din/homework_68_rashid_gulamov#12]
Для чего это нужно
Необходимо для редактирования, обновления и удаления записей в базе данных.
Как это сделать
Создать представления для редактирования, обновления и удаления записей вакансии. Прописать к ним формы, шаблоны и пути.

Критерии приема
Корректное отображение данных вакансии в браузере.
При правильном отображении введенных данных в браузере работа принимается.
Планируемое время 4 часа.

**Comment by kurentaev** [comment]
Задача завершена. Затраченное время - около 4 дня. Прошу принять на проверку.

**Comment by Rashid-ad-din** [comment]
Задача выполнена в полной мере. Работа принимается.
