### ISSUE TITLE
Создание шаблонов, представлений, форм и путей к моделям вакансии и отклика.

### ISSUE THREAD

**Issue by kurentaev** [Rashid-ad-din/homework_68_rashid_gulamov#22]
Для чего это нужно
Создание шаблонов, представлений, форм и путей к моделям вакансии и отклика позволит пользователю видеть все введенные данные в окне браузера.
Как это сделать
Создать представления для создания и просмотра вакансии. Прописать к ним формы, шаблоны и пути.

Критерии приема
Корректное отображение данных вакансии в браузере.
При правильном отображении введенных данных в браузере работа принимается.
Планируемое время 4 часа.

**Comment by kurentaev** [comment]
Задача завершена. Затраченное время - около 12 часов. Прошу принять на проверку.

**Comment by Rashid-ad-din** [comment]
Задача выполнена в полной мере. Работа принимается.
