### ISSUE TITLE
Стилизация проекта

### ISSUE THREAD

**Issue by kurentaev** [Rashid-ad-din/homework_68_rashid_gulamov#23]
Для чего это нужно
Необходимо для корректного отображения данных в окне браузера.
Как это сделать
Прописать стили, скрипты к шаблонам проекта.

Критерии приема
Корректное отображение данных в браузере.
При правильном отображении введенных данных в браузере работа принимается.
Планируемое время 6 часа.

**Comment by kurentaev** [comment]
Задача завершена. Затраченное время - около 8 часов. Прошу принять на проверку.

**Comment by Rashid-ad-din** [comment]
Задача выполнена в полной мере. Работа принимается.
