### ISSUE TITLE
Общая проверка проекта

### ISSUE THREAD

**Issue by kurentaev** [Rashid-ad-din/homework_68_rashid_gulamov#25]
Для чего это нужно
Для проверки работоспособности проекта.
Как это сделать
При создании отклика, в модели вакансии в поле отклика добавляется запись. 
После этого необходимо создать модель, которая будет хранить данные об отклике, сообщении, отправителе и дате создания.
Критерии приема
Корректное отображение данных браузере.
При правильном отображении введенных данных в браузере работа принимается.
Планируемое время 1 час.

**Comment by kurentaev** [comment]
Задача завершена. Затраченное время - около 1 часа. Прошу принять на проверку.

**Comment by Rashid-ad-din** [comment]
Задача выполнена в полной мере. Работа принимается.
