### ISSUE TITLE
Создание чата.

### ISSUE THREAD

**Issue by Rashid-ad-din** [Rashid-ad-din/homework_68_rashid_gulamov#29]
**Для чего это нужно**
Чат обеспечивает онлайн переписку между работодателем и соискателем.

**Как это сделать**
Создать страницы чата. Создание моделей Responde и RespondeMessage.
Страница личного профиля должна быть доступна по адресу host/hh/user/

_Форма создания Responde включает следующие поля:_
Резюме *
Вакансия *

_Форма смены пароля включает в себя следующий набор полей:_
Отклик *
Автор *
Текст сообщения *
Запись создана *
Запись изменена *

**Критерии приема**
Страница чата поделена на три части (row-col). Слева блок с данными резюме, посередине чат и справа блок с данными вакансии.
В блоке чат отображается автор сообщения и само сообщение, а также кнопка удалить сообщение, после нажатия которой, выводится модалка о подтверждении удаления, при подтверждении удаляется. Отображается вся переписка. Ниже имеется текстовое поле для заполнения и кнопка отправить сообщение.

Планируемое время 4 часа.

**Comment by kurentaev** [comment]
Задача выполнена в полной мере. Работа принимается.
