### ISSUE TITLE
Переопределение путей. Внесение соответствующих изменений во вьюшки и шаблоны.

### ISSUE THREAD

**Issue by Rashid-ad-din** [Rashid-ad-din/homework_68_rashid_gulamov#31]
**Для чего это нужно**
Переопределение путей улучшит читабельность кода, улучшит понимание какие параметры куда передавать.

**Как это сделать**
Переопределить пути в urls. Во вьюшках настроить прием параметров. В шаблонах определить какие параметры и куда передавать.

**Критерии приема**
Навигация по страницам всего проекта должна происходить свободно с отражением корректных данных.

Планируемое время 1 час.

**Comment by Rashid-ad-din** [comment]
Задача выполнена. Затраченное время - 2 часа.

**Comment by kurentaev** [comment]
Задача выполнена в полной мере. Работа принимается.
