### ISSUE TITLE
Создание моделей резюме + опыт  + образование и чойзов категорий

### ISSUE THREAD

**Issue by Rashid-ad-din** [Rashid-ad-din/homework_68_rashid_gulamov#4]
**Для чего это нужно :** 
Создание данных моделей обеспечит дальнейшее создание экземпляров данных моделей. Таким образом кандидаты могут создавать полноценное резюме для поиска работы и полноценного взаимодействия с работодателями на рынке труда.

**Как это сделать:** 
Создание моделей Resume, CategoryChoices, Education, Experience в приложении webapp.

> `Возможность создания резюме. Ниже приведен пример разделения и основные модули для резюме. Здесь стоит разобраться немного подробнее:
> 
> Есть основная часть резюме т.е базовая информация о пользователе, где пользователь выбирает категорию вакансии, задает название резюме (должности) ожидаемый уровень заработной платы, и указывает ссылки на соцсети, контактные данные :
> p.s если какие то данные не указаны то не нужно отображать их на странице при просмотре резюме.
> 
> Так же есть множество однотипных модулей которые связаны с основным резюме. В ходе создания резюме вы можете добавить неограниченное количество таких модулей. Каждый из них должен описывать опыт работы.  Годы работы, название компании, должность, обязанности.
> 
> Аналогичные модули для указания образования соискателя или же пройденных курсов повышения квалификации`

***Поля для моделей:***

****Resume:****
- Автор *
- Имя *
- Фамилия *
- Позиция *
- Сфера деятельности (Категория) *
- Уровень дохода *
- Телефон *
- Email *
- Telegram *
- Facebook
- Linkedin
- Опыт работы (M2M webapp.Experiences)
- Образование (webapp.Educations)
- Обо мне
- Активность резюме (отражать или нет данное резюме) *

****CategoryChoices:****
Произвольные чойсы, отражающие сферу деятельности в которой работает кандидат.

****Education:****
- Наименование образовательного учреждения *
- Дата начала обучения *
- Дата окончания обучения *
- Специальность *
- Дополнительная информация

****Experience :****
- Компания *
- Стаж *
- Дата начала *
- Дата увольнения *
- Позиция *
- Обязанности *
- Дополнительная информация

**Критерии приема :** 
При создании экземпляров моделей непосредственно в таблицах они не смогут быть созданы без заполнения обязательных полей.
При добавлении образования и опыта в соответствующих таблицах должны создаться данные связи. Данный функционал позволит в дальнейшем, например, выводить несколько образований в отдельных модулях в браузере (предположительно циклом), а также указать несколько мест обучений и/или компаний в которых работал соискатель.

Планируемое время : 4 часа.

**Comment by kurentaev** [comment]
Задача выполнена в полной мере. Работа принимается.
