### ISSUE TITLE
Расширение CRUD операций модели Account

### ISSUE THREAD

**Issue by Rashid-ad-din** [Rashid-ad-din/homework_68_rashid_gulamov#5]
**Для чего это нужно**
Добавление функционала просмотра личного профиля в личном кабинете, изменение данных профиля, а также смена пароля.

**Как это сделать**
Создать страницы личного кабинета, изменения данных, изменения пароля.
Страница личного профиля должна быть доступна по адресу host/auth/profile/<int:pk>/
Страница изменения данных должна быть доступна по адресу host/auth/profile/<int:pk>/change/
Страница изменения пароля должна быть доступна по адресу hostauth/profile/9/password-change/

Форма изменения данных включает в себя следующий набор полей:
Email *
Номер телефона *
Имя / Название компании *
Файловое поле (Фото)

Форма смены пароля включает в себя следующий набор полей:
Пароль *
Подтверждение пароля *

**Критерии приема**

***Профиль***
При авторизация, появляется иконка профиля со ссылкой на страницу личного кабинета.
В личном кабинете отображаются личные данные пользователя и аватар, также появляется возможность изменения данных и смены пароля с соответствующими ссылками.

***Изменение данных***
Добавлена ссылка на изменение данных=.
Переход по ссылке открывает форму изменения данных.
При корректном заполнении формы нажатие на кнопку производит сохранение данных пользователя.

***Изменение пароля***
Добавлена ссылка на изменение данных.
При корректном заполнении формы нажатие на кнопку производит изменение пароля пользователя.

Планируемое время 3,5 часа.

**Comment by kurentaev** [comment]
Задача выполнена в полной мере. Работа принимается.
