### ISSUE TITLE
Создание моделей вакансии и отклика

### ISSUE THREAD

**Issue by kurentaev** [Rashid-ad-din/homework_68_rashid_gulamov#7]
Для чего это нужно
Модель вакансии позволит работодателю добавлять свои записи (вакансии) в базу данных, на которые в дальнейшем соискатель может ссылаться.
Как это сделать
В файле моделей приложения webapp, создать модели Vacancy и Respond с полями приведенными ниже в описании. Зарегистрировать модель в админ панели. 
При создании вакансии, указываются следующие поля: 
    1. Название вакансии
    2. Заработная плата
    3. Детальное описание вакансии включающее в себя требования по знаниям соискателя.
    4. Указание требуемого опыта работы от и до (лет)
    5. Категория вакансии, выбирается из выпадающего списка.
    6. Видимость вакансии

При создании отклика, в модели вакансии в поле отклика добавляется запись. 
Критерии приема
Корректное отображение данных вакансии в админ-панели.
При правильном отображении введенных данных в админ-панели работа принимается.
Планируемое время 4 часа.

**Comment by kurentaev** [comment]
Задача завершена. Затраченное время - около 8 часов. Прошу принять на проверку.

**Comment by Rashid-ad-din** [comment]
Задача выполнена в полной мере. Работа принимается.
